<a href="https://colab.research.google.com/github/Serahverg-8/Deep-Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
torch.__version__

'2.0.1+cu118'

torch.tensor class : A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

In [2]:

#intro to tensors

#creating tensors - torch.tensor

In [4]:
#scalar tensor

scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
#attributes:
scalar.ndim
#no dimensions

0

In [6]:
scalar.item()

#returns the scalar value. This only works for scalar

7

In [7]:
## Vector -- > magnitude and direction (usually one dimension aka one feature taking up one axis on the graph). It usually has more than one value

In [8]:
vector=torch.tensor([7,2])

In [10]:
vector.ndim
# vector is 1D . just needs rows to navigate to the value

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
#like an array it indicates its a 2x1 vector

In [41]:
MATRIX = torch.tensor([[2,5],[3,6]])

In [42]:
MATRIX.ndim
# matrix is 2Dimensional ---> rows and columns to navigate

2

In [43]:
MATRIX.shape

torch.Size([2, 2])

In [44]:
MATRIX[0]

tensor([2, 5])

In [45]:
MATRIX[1][0]

tensor(3)

In [28]:
TENSOR = torch.tensor([[1,4,5],
 [3,8,9],
  [1,2,5]])

In [29]:
TENSOR.shape

torch.Size([3, 3])

In [30]:
TENSOR.ndim

#still only rows and columns to navigate. Usially number or square brackets starting or ending gives the dimensions

2

In [36]:
TENSOR_2= torch.tensor([[[1,4,5],
                          [3,8,9],
                          [1,2,5]]
                        ,
                        [[1,5,3],
                        [2,5,4],
                        [3,6,4]]])

In [37]:
TENSOR_2.shape

torch.Size([2, 3, 3])

In [38]:
TENSOR_2.ndim

3

In [39]:
TENSOR_2[1]

tensor([[1, 5, 3],
        [2, 5, 4],
        [3, 6, 4]])

In [40]:
TENSOR_2[1][1]

tensor([2, 5, 4])

vector and scalars are usually in lowercase. Matrices and Tensors are names in capitals

## Random Tensors

We need Random tensors for initializing random numbers. These random numbers are updated by feedback and updated accordingly

In [49]:
random_tensor = torch.rand(4,3,4)

In [50]:
random_tensor

tensor([[[0.4266, 0.3192, 0.8582, 0.4401],
         [0.2106, 0.4440, 0.5684, 0.1160],
         [0.4912, 0.0106, 0.4384, 0.1223]],

        [[0.0777, 0.7243, 0.3246, 0.7889],
         [0.7825, 0.3582, 0.2132, 0.5945],
         [0.1879, 0.1238, 0.8608, 0.4446]],

        [[0.4110, 0.9674, 0.9245, 0.0986],
         [0.1642, 0.1151, 0.9795, 0.0860],
         [0.0700, 0.5956, 0.1346, 0.5640]],

        [[0.0037, 0.5055, 0.7479, 0.5169],
         [0.1673, 0.8899, 0.0620, 0.6418],
         [0.8801, 0.8797, 0.5180, 0.7867]]])

In [51]:
random_tensor.ndim

3

In [56]:

#images generally have (r,g,b) values combined --> size * (r,g,b)
random_image_tensor= torch.rand(3,224,224)

# the 3 here represents the color channels whose combination can get almost every color

In [57]:
random_image_tensor.shape

torch.Size([3, 224, 224])

#tensor of zeros or ones

In [74]:
zeros = torch.zeros(3,1)

In [75]:
zeros

tensor([[0.],
        [0.],
        [0.]])

In [76]:
zeros.dtype

torch.float32

We usually see zeros for masking!

Default datatype is float

In [77]:
random_tensor = torch.rand(3,4)

In [78]:
random_tensor

tensor([[0.3367, 0.2726, 0.5329, 0.2699],
        [0.4689, 0.9027, 0.5801, 0.3239],
        [0.7530, 0.6985, 0.6738, 0.4660]])

In [79]:
zeros*random_tensor
#element wise
# it broad casts to the other columns

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones

In [88]:
ones=torch.ones(3,1)*2

In [89]:
ones

tensor([[2.],
        [2.],
        [2.]])

In [90]:
ones*random_tensor

tensor([[0.6734, 0.5451, 1.0659, 0.5397],
        [0.9378, 1.8054, 1.1603, 0.6477],
        [1.5060, 1.3969, 1.3476, 0.9320]])

#RANGE

In [91]:
torch.range(1,16)

<ipython-input-91-3e8b614ad210>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,16)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])

In [92]:
torch.arange(1,16)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
torch.arange(1,16,3)

tensor([ 1,  4,  7, 10, 13])

#Tensor\s LIKE

Want to create a tensor with the same shape as another, we can use tensor like

In [100]:
new_tensor_zeros= torch.zeros_like(input=random_tensor)

In [101]:
new_tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [103]:
new_tensor_rand= torch.rand_like(input=random_tensor)
new_tensor_rand

tensor([[0.5552, 0.6621, 0.4967, 0.1565],
        [0.2800, 0.8042, 0.4249, 0.6502],
        [0.1516, 0.7520, 0.7088, 0.2619]])

In [104]:
new_tensor_ones= torch.ones_like(input=random_tensor)
new_tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#DATATYPES

default --> float 32 even if we speciy none.

We will mostly run into the error wrt to datatype, shape, and device

In [105]:

t1= torch.rand(3,3,
               dtype=None, #datatype 32 and 16 bit floats most used
               device=None, # default = cpu
               requires_grad=False) #this is to track the gradients -- will get into it int he next bits
t1.dtype

torch.float32

In [111]:
t1

tensor([[0.9432, 0.1794, 0.4638],
        [0.3706, 0.3061, 0.6213],
        [0.3251, 0.5134, 0.7887]])

The above parmeters are the most imp ones when we create tensors

the 32 bit float is of higher precision hence more detail. Each number has 32 bits.
Number that take up less memory , we can change it to 16 bits.

In [107]:
#converting 32 to 16 bit float datatype
float_16_tensor=t1.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [110]:
output=float_16_tensor * t1
output
#elemetwise not dot product

tensor([[0.8898, 0.0322, 0.2151],
        [0.1373, 0.0937, 0.3862],
        [0.1057, 0.2634, 0.6220]])

In [112]:
output.dtype #typrcasted to the higher one

torch.float32

#other datatypes
https://pytorch.org/docs/stable/tensors.html