<a href="https://colab.research.google.com/github/Serahverg-8/Deep-Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
torch.__version__

'2.0.1+cu118'

torch.tensor class : A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

In [2]:

#intro to tensors

#creating tensors - torch.tensor

In [4]:
#scalar tensor

scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
#attributes:
scalar.ndim
#no dimensions

0

In [6]:
scalar.item()

#returns the scalar value. This only works for scalar

7

In [7]:
## Vector -- > magnitude and direction (usually one dimension aka one feature taking up one axis on the graph). It usually has more than one value

In [8]:
vector=torch.tensor([7,2])

In [10]:
vector.ndim
# vector is 1D . just needs rows to navigate to the value

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
#like an array it indicates its a 2x1 vector

In [17]:
Matrix = torch.tensor([[2,5],[3,6]])

In [18]:
Matrix.ndim
# matrix is 2Dimensional ---> rows and columns to navigate

2

In [19]:
Matrix.shape

torch.Size([2, 2])

In [20]:
Matrix[0]

tensor([2, 5])

In [21]:
Matrix[1][0]

tensor(3)

In [28]:
TENSOR = torch.tensor([[1,4,5],
 [3,8,9],
  [1,2,5]])

In [29]:
TENSOR.shape

torch.Size([3, 3])

In [30]:
TENSOR.ndim

#still only rows and columns to navigate. Usially number or square brackets starting or ending gives the dimensions

2

In [36]:
TENSOR_2= torch.tensor([[[1,4,5],
                          [3,8,9],
                          [1,2,5]]
                        ,
                        [[1,5,3],
                        [2,5,4],
                        [3,6,4]]])

In [37]:
TENSOR_2.shape

torch.Size([2, 3, 3])

In [38]:
TENSOR_2.ndim

3

In [39]:
TENSOR_2[1]

tensor([[1, 5, 3],
        [2, 5, 4],
        [3, 6, 4]])

In [40]:
TENSOR_2[1][1]

tensor([2, 5, 4])