<a href="https://colab.research.google.com/github/Serahverg-8/Deep-Learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
torch.__version__

'2.0.1+cu118'

torch.tensor class : A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

In [2]:

#intro to tensors

#creating tensors - torch.tensor

In [3]:
#scalar tensor

scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
#attributes:
scalar.ndim
#no dimensions

0

In [5]:
scalar.item()

#returns the scalar value. This only works for scalar

7

In [6]:
## Vector -- > magnitude and direction (usually one dimension aka one feature taking up one axis on the graph). It usually has more than one value

In [7]:
vector=torch.tensor([7,2])

In [8]:
vector.ndim
# vector is 1D . just needs rows to navigate to the value

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#like an array it indicates its a 2x1 vector

In [11]:
MATRIX = torch.tensor([[2,5],[3,6]])

In [12]:
MATRIX.ndim
# matrix is 2Dimensional ---> rows and columns to navigate

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[0]

tensor([2, 5])

In [15]:
MATRIX[1][0]

tensor(3)

In [16]:
TENSOR = torch.tensor([[1,4,5],
 [3,8,9],
  [1,2,5]])

In [17]:
TENSOR.shape

torch.Size([3, 3])

In [18]:
TENSOR.ndim

#still only rows and columns to navigate. Usially number or square brackets starting or ending gives the dimensions

2

In [19]:
TENSOR_2= torch.tensor([[[1,4,5],
                          [3,8,9],
                          [1,2,5]]
                        ,
                        [[1,5,3],
                        [2,5,4],
                        [3,6,4]]])

In [20]:
TENSOR_2.shape

torch.Size([2, 3, 3])

In [21]:
TENSOR_2.ndim

3

In [22]:
TENSOR_2[1]

tensor([[1, 5, 3],
        [2, 5, 4],
        [3, 6, 4]])

In [23]:
TENSOR_2[1][1]

tensor([2, 5, 4])

vector and scalars are usually in lowercase. Matrices and Tensors are names in capitals

## Random Tensors

We need Random tensors for initializing random numbers. These random numbers are updated by feedback and updated accordingly

In [24]:
random_tensor = torch.rand(4,3,4)

In [25]:
random_tensor

tensor([[[0.5515, 0.7263, 0.2682, 0.3163],
         [0.2438, 0.3312, 0.2300, 0.1841],
         [0.8873, 0.3298, 0.4071, 0.1626]],

        [[0.9127, 0.8541, 0.3730, 0.8558],
         [0.0768, 0.6424, 0.4211, 0.4993],
         [0.9764, 0.4986, 0.2247, 0.4645]],

        [[0.3747, 0.4806, 0.6228, 0.3213],
         [0.6434, 0.4257, 0.7607, 0.5859],
         [0.2720, 0.9301, 0.8806, 0.6726]],

        [[0.4720, 0.3371, 0.8637, 0.2848],
         [0.1665, 0.1379, 0.3087, 0.1398],
         [0.7760, 0.7324, 0.2040, 0.9042]]])

In [26]:
random_tensor.ndim

3

In [27]:

#images generally have (r,g,b) values combined --> size * (r,g,b)
random_image_tensor= torch.rand(3,224,224)

# the 3 here represents the color channels whose combination can get almost every color

In [28]:
random_image_tensor.shape

torch.Size([3, 224, 224])

#tensor of zeros or ones

In [29]:
zeros = torch.zeros(3,1)

In [30]:
zeros

tensor([[0.],
        [0.],
        [0.]])

In [31]:
zeros.dtype

torch.float32

We usually see zeros for masking!

Default datatype is float

In [32]:
random_tensor = torch.rand(3,4)

In [33]:
random_tensor

tensor([[0.2347, 0.6046, 0.5405, 0.4805],
        [0.6736, 0.0888, 0.9962, 0.7914],
        [0.7544, 0.1512, 0.7738, 0.3715]])

In [34]:
zeros*random_tensor
#element wise
# it broad casts to the other columns

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones

In [35]:
ones=torch.ones(3,1)*2

In [36]:
ones

tensor([[2.],
        [2.],
        [2.]])

In [37]:
ones*random_tensor

tensor([[0.4694, 1.2091, 1.0810, 0.9610],
        [1.3472, 0.1775, 1.9923, 1.5828],
        [1.5088, 0.3025, 1.5476, 0.7430]])

#RANGE

In [38]:
torch.range(1,16)

<ipython-input-38-3e8b614ad210>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,16)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])

In [39]:
torch.arange(1,16)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
torch.arange(1,16,3)

tensor([ 1,  4,  7, 10, 13])

#Tensor\s LIKE

Want to create a tensor with the same shape as another, we can use tensor like

In [41]:
new_tensor_zeros= torch.zeros_like(input=random_tensor)

In [42]:
new_tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
new_tensor_rand= torch.rand_like(input=random_tensor)
new_tensor_rand

tensor([[0.2186, 0.8876, 0.8446, 0.4832],
        [0.2201, 0.5424, 0.6511, 0.7310],
        [0.0591, 0.0381, 0.3190, 0.2222]])

In [44]:
new_tensor_ones= torch.ones_like(input=random_tensor)
new_tensor_ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#DATATYPES

default --> float 32 even if we speciy none.

We will mostly run into the error wrt to datatype, shape, and device

In [45]:

t1= torch.rand(3,3,
               dtype=None, #datatype 32 and 16 bit floats most used
               device=None, # default = cpu
               requires_grad=False) #this is to track the gradients -- will get into it int he next bits
t1.dtype

torch.float32

In [46]:
t1

tensor([[0.9312, 0.3930, 0.1815],
        [0.4897, 0.9536, 0.7019],
        [0.6250, 0.8577, 0.2673]])

The above parmeters are the most imp ones when we create tensors

the 32 bit float is of higher precision hence more detail. Each number has 32 bits.
Number that take up less memory , we can change it to 16 bits.

In [47]:
#converting 32 to 16 bit float datatype
float_16_tensor=t1.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [48]:
output=float_16_tensor * t1
output
#elemetwise not dot product

tensor([[0.8671, 0.1545, 0.0329],
        [0.2398, 0.9094, 0.4925],
        [0.3907, 0.7358, 0.0715]])

In [49]:
output.dtype #typrcasted to the higher one

torch.float32

some operations will run into error. Interger and float 32 and int 32. When we multiply them it works, int and torch.long

#other datatypes
https://pytorch.org/docs/stable/tensors.html

# Tensor Attributes

getting the right info for errors from tensors:   


tensors.dtype, tensors.shape,tensors.device





In [50]:
random_tensor.shape

torch.Size([3, 4])

In [51]:
random_tensor.device

device(type='cpu')

size - function. shape is an attribute

#TENSOR OPERATIONS

Additon, sub, multiplication and division , matrix multiplication ...

In [52]:
#additon

a1=torch.tensor([[1,2,3],[4,5,6]])

In [53]:
a1+10

a1*10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [54]:
a1/0.5

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [55]:
a2=torch.tensor([[3,6,3],[4,6,9]])

In [56]:
a1+a2

tensor([[ 4,  8,  6],
        [ 8, 11, 15]])

In [57]:
a1*a2
#elementwise

tensor([[ 3, 12,  9],
        [16, 30, 54]])

In [58]:
a3 = torch.tensor([[1,4],
      [2,6],
      [8,4]])

inbuilt torch functions

torch.mul(a1,10)
torch.add(a1,3)

#matrix multiplication

Differes from element wise. From neural networks we usually use a lot of matrix multiplication. Here we need to use the dot product.
We can use the  *torch.matmul()* or *@*

In [63]:
%%time
# to test the time
torch.matmul(a1,a3)

#  or
torch.mm(a1,a3)

#mm is an alias for matmul

CPU times: user 151 µs, sys: 0 ns, total: 151 µs
Wall time: 156 µs


tensor([[29, 28],
        [62, 70]])

In [64]:
# 2 X 3. and 3 X. 2 = 2 x 2

Rules for mat mul:  ** Inner dimensions must match ** . Matrices are always 2D

In [65]:
#to transpose:

a1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

#tensor aggregation- min max sum etc

In [66]:
x=torch.arange(2,36,3)

#

In [67]:
x

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35])

In [68]:
torch.min(x)
#or x.min()

tensor(2)

In [69]:
torch.max(a1)
#or x.max()

tensor(6)

In [70]:
a2.dtype

torch.int64

torch.mean(a1)
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
so typecast to float

long is int64 change it to float32

In [71]:
torch.mean(a2.type(torch.float32))
#or
a2.type(torch.float32).mean()

tensor(5.1667)

To get the position of min and max -- > use argmin and argmax

In [72]:
x

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35])

In [73]:
x.argmin()

tensor(0)

In [74]:
a2

tensor([[3, 6, 3],
        [4, 6, 9]])

In [75]:
a2.argmax()

tensor(5)

# REshaping ,stacking,squeezing and unsqueezing



1.   Reshaping to another shape

2.   View:  get a veiw of the tensor into a cetain shape but keep the same memory

3. Stacking. Combining tensors:vertically or horizontally . torchvstach and torchhstach

4. squeeze and unsqueeze: removes or adds one dimension to the tensor

5. permute view of the input with dimensions a certain way


In [86]:
x = torch.arange(1.1,3.5,0.2)
x

tensor([1.1000, 1.3000, 1.5000, 1.7000, 1.9000, 2.1000, 2.3000, 2.5000, 2.7000,
        2.9000, 3.1000, 3.3000])

In [87]:
x.shape

torch.Size([12])

In [89]:
#reshape
# has to have the same number of elements
x.reshape(1,12)

tensor([[1.1000, 1.3000, 1.5000, 1.7000, 1.9000, 2.1000, 2.3000, 2.5000, 2.7000,
         2.9000, 3.1000, 3.3000]])

In [81]:
#here we added another dimension. hence two [[]]

In [94]:
#changing the view
z= x.view(4,3)

z

tensor([[1.1000, 1.3000, 1.5000],
        [1.7000, 1.9000, 2.1000],
        [2.3000, 2.5000, 2.7000],
        [2.9000, 3.1000, 3.3000]])

In [95]:
x

tensor([1.1000, 1.3000, 1.5000, 1.7000, 1.9000, 2.1000, 2.3000, 2.5000, 2.7000,
        2.9000, 3.1000, 3.3000])

In [102]:
z = z.reshape(3,2,2)

In [103]:
#remember: changing an element in z will change the element in x as they have the same memory

z.shape

torch.Size([3, 2, 2])

In [104]:
z[0][0][0] =13.6

In [105]:
print(z,"\n",x)

tensor([[[13.6000,  1.3000],
         [ 1.5000,  1.7000]],

        [[ 1.9000,  2.1000],
         [ 2.3000,  2.5000]],

        [[ 2.7000,  2.9000],
         [ 3.1000,  3.3000]]]) 
 tensor([13.6000,  1.3000,  1.5000,  1.7000,  1.9000,  2.1000,  2.3000,  2.5000,
         2.7000,  2.9000,  3.1000,  3.3000])


In [ ]:
#so although they are in different shapes , they still have he same values

In [111]:
##stacking - dim default 0

torch.stack([x,x,x],dim = 0)

#vertically stacking rowwise

tensor([[13.6000,  1.3000,  1.5000,  1.7000,  1.9000,  2.1000,  2.3000,  2.5000,
          2.7000,  2.9000,  3.1000,  3.3000],
        [13.6000,  1.3000,  1.5000,  1.7000,  1.9000,  2.1000,  2.3000,  2.5000,
          2.7000,  2.9000,  3.1000,  3.3000],
        [13.6000,  1.3000,  1.5000,  1.7000,  1.9000,  2.1000,  2.3000,  2.5000,
          2.7000,  2.9000,  3.1000,  3.3000]])

In [113]:

torch.stack([x,x,x],dim = 1)
#column wise stacking

tensor([[13.6000, 13.6000, 13.6000],
        [ 1.3000,  1.3000,  1.3000],
        [ 1.5000,  1.5000,  1.5000],
        [ 1.7000,  1.7000,  1.7000],
        [ 1.9000,  1.9000,  1.9000],
        [ 2.1000,  2.1000,  2.1000],
        [ 2.3000,  2.3000,  2.3000],
        [ 2.5000,  2.5000,  2.5000],
        [ 2.7000,  2.7000,  2.7000],
        [ 2.9000,  2.9000,  2.9000],
        [ 3.1000,  3.1000,  3.1000],
        [ 3.3000,  3.3000,  3.3000]])

##squeeze -

Returns a tensor with all specified dimensions of input of size 1 removed.


In [128]:
y= torch.arange(1,10)
y

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
y=y.reshape(1,1,9)

In [130]:
y.shape
print("shape now is ",y.shape)

shape now is  torch.Size([1, 1, 9])


In [132]:
y= y.squeeze()

print("after squuezing, shape becomes ",y.squeeze().shape)

after squuezing, shape becomes  torch.Size([9])


In [133]:
#removes all dimensions with 1: basically removes unwanted dimensions

##unsqueeze

In [134]:
y


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
y.unsqueeze(dim=0)
#( rows, columns, .....)
#(dim=0,dim=1,dim=2....)
print(y.unsqueeze(dim=0),y.unsqueeze(dim=0).shape)

#adden one to row [1,9]

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


# permute - rearrange the dimensions

In [144]:
z=torch.arange(1,25).reshape(3,4,2)
z




tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]])

innermost[] has 2 elements. middle[] has 4 elelments , outtermost[] has 3 chunks

In [150]:
print("first=" ,z.shape , "\n\npermuted=",z.permute(2,1,0),"\n\nnew shape=",z.permute(2,1,0).shape)
#(here the 2,1,0 represent the indices of the shape(dimensions))


first= torch.Size([3, 4, 2]) 

permuted= tensor([[[ 1,  9, 17],
         [ 3, 11, 19],
         [ 5, 13, 21],
         [ 7, 15, 23]],

        [[ 2, 10, 18],
         [ 4, 12, 20],
         [ 6, 14, 22],
         [ 8, 16, 24]]]) 

new shape= torch.Size([2, 4, 3])


Remember, permute is a view and hence will share the same mem

In [151]:
#indenxing and selecting

z

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]])

In [155]:
z.shape

torch.Size([3, 4, 2])

In [154]:

#we need to work with 3 , 4 and 2 dimensions

#all rows and 1st column
z[:,1]

tensor([[ 3,  4],
        [11, 12],
        [19, 20]])

In [156]:
#we need to work with 3 , 4 and 2 dimensions
z[1,0:2,0]



tensor([ 9, 11])

In [157]:
z[1][0:2][0]

tensor([ 9, 10])

#Pytorch and Numpy

array to torch

In [158]:
import numpy as np
x=np.arange(1,10)

In [159]:
x.dtype

dtype('int64')

In [160]:
tensor= torch.from_numpy(x)

tensor.dtype

torch.int64

So torch uses the same datatype as numpy that it is converting.

In [163]:
tensor =tensor.type(torch.float32)

In [165]:
#tensor to numpy

print("tensors dtype=",tensor.dtype)

y=tensor.numpy()

print("numpys dtype=",y.dtype)

tensors dtype= torch.float32
numpys dtype= float32


numpy also mimics the tensors dtype after conversion

#Seed value

In [167]:
seed=42

torch.manual_seed(seed=seed)

In [172]:
torch.manual_seed(seed=seed)
A= torch.rand(3,3)
A

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [173]:
torch.manual_seed(seed=seed)
B= torch.rand(3,3)
B

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [174]:
# both are the same: limiting the randomness for reproducible code/results on different systems

# GPU

GPU's help with faster computation. (Rent or buy etc)'.
Cloud computing -- > GCP , AWZ etc
We will use google colab for free now.

https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Sun Aug 27 23:23:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
#checking gpu with pytorch
#changed runtime herevso import again
import torch
torch.cuda.is_available()

True

In [8]:
## setting up device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"

In [9]:
device

'cuda'

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
# putting models/tensors on the gpu --. better

In [10]:
tensor = torch.arange(1,11)

In [11]:
tensor.device
#default cpu

device(type='cpu')

In [12]:
tensor_gpu = tensor.to(device)

In [13]:
tensor_gpu.device

device(type='cuda', index=0)

In [15]:
#to method to send to GPU is frequently used.

Remember : numpy cannot run on gpus. so is a tensor is on GPU, you cannot convert it to numpy. you will have to transfer it back to cpu and then
convert it to numpy.

In [18]:
back_to_cpu = tensor_gpu.cpu().numpy()

#.cpu is used here